FROM openjdk:17
ARG JAR_FILE=/build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENV SPRING_PROFILES_ACTIVE=docker
ENV JWT_SECRET_KEY=4iLaz4RBs9F0g1WAVppByh0uH/oeT6yT0zWzLx8fGPE
ENV JWT_REFRESH_TOKEN_EXPIRATION=86400000
ENV JWT_ACCESS_TOKEN_EXPIRATION=60000
ENTRYPOINT ["java","-jar", "/app.jar"]